/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.accessibility.AccessibleContext;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.LineBorder;
import PizzaIngredients.Dough;
import PizzaIngredients.Ingredient;

/**
 *
 * @author lenovo
 */
public class MixerFrame extends javax.swing.JFrame {

    private Dough pizzaDough;
    private Ingredient selected;
    private JLabel[] ingreds = new JLabel[6];

    /**
     * Creates new form Mixer
     */
    public MixerFrame() {
        initComponents();
        pizzaDough = new Dough();
        rootPane.setFocusable(true);
        int c = 0;
        ingreds[c++] = this.Flour;
        ingreds[c++] = this.yeast;
        ingreds[c++] = this.water;
        ingreds[c++] = this.sugar;
        ingreds[c++] = this.salt;
        ingreds[c++] = this.oil;

    }

    public JLabel getChat() {
        return chat;
    }

    public JLabel getFlour() {
        return Flour;
    }

    public void setFlour(JLabel Flour) {
        this.Flour = Flour;
    }

    public JTextArea getMixer() {
        return Mixer;
    }

    public void setMixer(JTextArea Mixer) {
        this.Mixer = Mixer;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getjTextArea1() {
        return actionInfo;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.actionInfo = jTextArea1;
    }

    public JLabel getSalt() {
        return salt;
    }

    public void setSalt(JLabel salt) {
        this.salt = salt;
    }

    public JLabel getSugar() {
        return sugar;
    }

    public void setSugar(JLabel sugar) {
        this.sugar = sugar;
    }

    public JLabel getWater() {
        return water;
    }

    public void setWater(JLabel water) {
        this.water = water;
    }

    public JLabel getYeast() {
        return yeast;
    }

    public void setYeast(JLabel yeast) {
        this.yeast = yeast;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sugar = new javax.swing.JLabel();
        Flour = new javax.swing.JLabel();
        yeast = new javax.swing.JLabel();
        water = new javax.swing.JLabel();
        salt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actionInfo = new javax.swing.JTextArea();
        amountSetter = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Mixer = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        stop = new javax.swing.JButton();
        mix = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        oil = new javax.swing.JLabel();
        chat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        sugar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/icons8-sugar-60.png"))); // NOI18N
        sugar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        sugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sugarMouseClicked(evt);
            }
        });

        Flour.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Flour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Flour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/icons8-flour-60.png"))); // NOI18N
        Flour.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        Flour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlourMouseClicked(evt);
            }
        });

        yeast.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        yeast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yeast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/icons8-yeast-60.png"))); // NOI18N
        yeast.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        yeast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yeastMouseClicked(evt);
            }
        });

        water.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        water.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/icons8-water-60.png"))); // NOI18N
        water.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        water.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waterMouseClicked(evt);
            }
        });

        salt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        salt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/icons8-salt-60.png"))); // NOI18N
        salt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        salt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saltMouseClicked(evt);
            }
        });

        actionInfo.setEditable(false);
        actionInfo.setColumns(20);
        actionInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        actionInfo.setRows(5);
        actionInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Information"));
        jScrollPane1.setViewportView(actionInfo);

        amountSetter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        amountSetter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40), 2), "Selecte item amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        amountSetter.setOpaque(true);

        Mixer.setEditable(false);
        Mixer.setBackground(new java.awt.Color(204, 204, 204));
        Mixer.setColumns(20);
        Mixer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Mixer.setRows(5);
        Mixer.setToolTipText("");
        Mixer.setBorder(javax.swing.BorderFactory.createMatteBorder(50, 6, 6, 6, new java.awt.Color(0, 0, 0)));
        Mixer.setMargin(new java.awt.Insets(0, -20, 0, 0));
        jScrollPane2.setViewportView(Mixer);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        stop.setBackground(new java.awt.Color(255, 0, 0));
        stop.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 255, 255));
        stop.setText("Stop");

        mix.setBackground(new java.awt.Color(0, 102, 51));
        mix.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mix.setForeground(new java.awt.Color(255, 255, 255));
        mix.setText("Mix");
        mix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mix, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stop)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stop, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(mix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setText("        ");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 7, 7, new java.awt.Color(0, 0, 0)));

        oil.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        oil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/icons8-olive-oil-64.png"))); // NOI18N
        oil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        oil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oilMouseClicked(evt);
            }
        });

        chat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/icons8-italy-60.png"))); // NOI18N
        chat.setText(": I feel somthing terrible is going to happen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(chat, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yeast, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Flour, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(amountSetter, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(amountSetter, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Flour, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yeast, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(chat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Dough getPizzaDough() {
        return pizzaDough;
    }

    public Ingredient getSelected() {
        return selected;
    }

    public JTextArea getInfo() {
        return actionInfo;
    }

    public JButton getMix() {
        return mix;
    }

    public JLabel getOil() {
        return oil;
    }

    public JButton getStop() {
        return stop;
    }

    public static int getEXIT_ON_CLOSE() {
        return EXIT_ON_CLOSE;
    }

    public JRootPane getRootPane() {
        return rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public JLabel[] getIngreds() {
        return ingreds;
    }

    public JLabel getAmountSetter() {
        return amountSetter;
    }

    public void setSelected(Ingredient selected) {
        this.selected = selected;
    }


    private void FlourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlourMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FlourMouseClicked

    private void yeastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yeastMouseClicked
        // TODO add your handling code here:s
    }//GEN-LAST:event_yeastMouseClicked

    private void waterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_waterMouseClicked

    private void sugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sugarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sugarMouseClicked

    private void saltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saltMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saltMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void mixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mixActionPerformed

    private void oilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_oilMouseClicked
    public void setLabelsColorsExept(Color c, int except) {
        for (int i = 0; i < 6; i++) {
            if (i == except) {
                ingreds[i].setBorder(BorderFactory.createLineBorder(c, 3));

                continue;
            }
            if (((LineBorder) ingreds[i].getBorder()).getLineColor().equals(Color.GREEN)) {
                continue;
            }
            ingreds[i].setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MixerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MixerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MixerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MixerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MixerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Flour;
    private javax.swing.JTextArea Mixer;
    private javax.swing.JTextArea actionInfo;
    private javax.swing.JLabel amountSetter;
    private javax.swing.JLabel chat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mix;
    private javax.swing.JLabel oil;
    private javax.swing.JLabel salt;
    private javax.swing.JButton stop;
    private javax.swing.JLabel sugar;
    private javax.swing.JLabel water;
    private javax.swing.JLabel yeast;
    // End of variables declaration//GEN-END:variables
}
